### ISSUE TITLE
Nickserv is down

### ISSUE THREAD

**Issue by Qqwwaann** [wetfish/services#9]
@itsrachelfish plz fix

**Comment by itsrachelfish** [comment]
This was the error message from the crash:

```
/home/services/services/node_modules/irc/lib/irc.js:759
                    throw err;
                          ^
TypeError: Cannot read property 'length' of undefined
    at Query._callback (/home/services/services/modules/nickserv.js:316:25)
    at Query.Sequence.end (/home/services/services/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol._validateEnqueue (/home/services/services/node_modules/mysql/lib/protocol/Protocol.js:218:6)
    at Protocol._enqueue (/home/services/services/node_modules/mysql/lib/protocol/Protocol.js:129:13)
    at Connection.query (/home/services/services/node_modules/mysql/lib/Connection.js:185:25)
    at Object.model.user.name (/home/services/services/core/model.js:221:25)
    at Object.nickserv._login (/home/services/services/modules/nickserv.js:314:20)
    at Object.nickserv._identify (/home/services/services/modules/nickserv.js:308:18)
    at Client.nickserv.client_message (/home/services/services/modules/nickserv.js:109:34)
    at Client.emit (events.js:117:20)
```
